name: thejoker

channels:
  - astropy
  - conda-forge

dependencies:
  - python=3
  # - astropy
  - astropy-helpers
  - numpy
  - matplotlib
  - scipy
  - h5py
  - sphinx
  - pandoc
  - nbconvert
  - ipykernel
  - cython
  - pip:
    - git+https://github.com/astropy/astropy
    - schwimmbad
    - emcee
    - nbsphinx
    - twobody
