name: thejoker

channels:
  - astropy

dependencies:
  - python=3
  - astropy
  - numpy
  - matplotlib
  - scipy
  - h5py
  - emcee
  - pip:
    - schwimmbad
    - git+https://github.com/adrn/TwoBody
