[build-system]

requires = ["setuptools",
            "setuptools_scm",
            "wheel",
            "extension-helpers",
            "scipy",
            "numpy",
            "cython",
            "twobody"]

build-backend = 'setuptools.build_meta'
