name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: ["ubuntu-latest", "macos-latest"]
        pymc-version: ["latest"]
        include:
          - os: ubuntu-latest
            python-version: "3.10"
            pymc-version: "5.10.0"  # Oldest pymc version
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Install hdf5 for tables (linux)"
        if: runner.os == 'ubuntu-latest'
        run: sudo apt-get install libhdf5-serial-dev

      - name : "Install hdf5 for tables (mac)"
        if: runner.os == 'macos-latest'
        run: brew install hdf5

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -e .[test]

      - name: Correct pymc version
        if: matrix.pymc-version != 'latest'
        run: |
          python -m pip install pymc==${{ matrix.pymc-version }}

      - name: Test package
        run: >-
          python -m pytest -ra --cov --cov-report=xml --cov-report=term --durations=20 .

      - name: Upload coverage report
        uses: codecov/codecov-action@v4.1.0