name: Tutorials
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

jobs:
  notebooks:
    name: "Build the notebooks for the docs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install -U pip wheel
          python -m pip install ".[tutorials]"

      - name: Execute the notebooks
        run: |
          cd docs
          CACHEDIR=$pwd/cache
          rm -rf $CACHEDIR
          export PYTENSOR_FLAGS=base_compiledir=$CACHEDIR
          python run_notebooks.py

      - uses: actions/upload-artifact@v3
        with:
          name: notebooks-for-${{ github.sha }}
          path: docs/examples

      - name: Trigger RTDs build
        if: ${{ github.event_name != 'pull_request' }}
        uses: dfm/rtds-action@v1.1.0
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}