name: Windows tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "Python 3.9 on ${{ matrix.os }}"
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest"]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install MSVC / Visual C++
        uses: ilammy/msvc-dev-cmd@v1

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9

      - name: Install build dependencies
        run: |
          choco install pandoc --no-progress
          conda create -n thejoker python=3.9 -q
          conda activate thejoker
          conda install mkl-service libpython m2w64-toolchain -q -y

      - name: Install thejoker and test dependencies
        run: |
          conda activate thejoker
          python -m pip install tox

      - name: Run tests
        run: |
          conda activate thejoker
          tox -e py37
